version: '3.8'

services:
  plebbit-cli:
    image: silkroadnomad/plebbit-cli:v0.0.1
    ports:
      - "9138:9138"
    volumes:
      - ./plebbit-cli/start-plebbit.sh:/start-plebbit.sh:ro
      - ./data/plebbit:/app/data
    command: ["sh", "-c", "/app/plebbit-cli/bin/run daemon --plebbitOptions.dataPath /app/data"]
